services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    environment:
      FLASK_ENV: production
      PORT: ${PORT:-5000}
    restart: unless-stopped
